name: Help me please!
description: Ask for help
title: "[Course Name]: What is your issue?"
labels: ["bug"]
assignees:
  - timrooke1991
body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking for help! An instructor, classmate or member of the BourneCoders community will get back to you shortly
  - type: input
    id: course
    attributes:
      label: Course Name
      description: What course is this issue related to?
      placeholder: Intro to Web Developer
    validations:
      required: true
  - type: input
    id: github
    attributes:
      label: Github Repo URL
      description: Where does this code live?
      placeholder: https://github.com/Bournecoders/help-me
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of laptop do you have?
      options:
        - Mac
        - Windows
        - Chromebook
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant error output
      description: Please copy and paste any error output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Have you asked Google about your problem? Or Stack Overflow?
      description: It is good practice to find possible solutions first before raising an issue. Some stuggle is good 😛
      options:
        - label: I have tried to solve find solutions for this problem independently
          required: true

